import type { Product } from '../types/models';

export const products: Product[] = [
  {
    id: 101,
    name: 'NovaBook Air 14',
    price: 32999,
    description: 'Ince govde, uzun pil omru ve gunluk is akislari icin dengeli performans sunan laptop modeli.',
    categoryId: 1,
    brandId: 1,
    stockCount: 18,
    imageUrl: 'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1200&q=80',
    summary: 'Ince tasarim ve uzun pil omru.',
    is_promoted: true,
  },
  {
    id: 102,
    name: 'Vertex Pro 16',
    price: 45999,
    description: 'Yuksek islem gucu ve buyuk ekrani ile tasarim ile yazilim islerinde kullanima uygun premium laptop.',
    categoryId: 1,
    brandId: 4,
    stockCount: 9,
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80',
    summary: 'Yuksek performansli premium laptop.',
    is_promoted: true,
  },
  {
    id: 103,
    name: 'QuantumEdge Work 15',
    price: 38999,
    description: 'Yuksek hizli SSD ve 32 GB RAM kombinasyonu ile coklu gorev kullaniminda akici deneyim sunar.',
    categoryId: 1,
    brandId: 6,
    stockCount: 14,
    imageUrl: 'https://images.unsplash.com/photo-1484788984921-03950022c9ef?auto=format&fit=crop&w=1200&q=80',
    summary: 'Coklu gorev odakli guclu laptop.',
    is_promoted: false,
  },
  {
    id: 201,
    name: 'PulseOne X7',
    price: 24999,
    description: '120 Hz ekran, hizli sarj ve gelismis kamera sistemi ile amiral gemisi telefon deneyimi sunar.',
    categoryId: 2,
    brandId: 2,
    stockCount: 26,
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80',
    summary: 'Kamera odakli amiral gemisi telefon.',
    is_promoted: true,
  },
  {
    id: 202,
    name: 'Arclight S10',
    price: 18999,
    description: 'Dengeli fiyat performans segmentinde AMOLED ekran ve guvenli biyometrik kilit ozellikleri sunar.',
    categoryId: 2,
    brandId: 3,
    stockCount: 34,
    imageUrl: 'https://images.unsplash.com/photo-1522273400909-fd1a8f77637e?auto=format&fit=crop&w=1200&q=80',
    summary: 'Dengeli ve hizli telefon.',
    is_promoted: false,
  },
  {
    id: 203,
    name: 'Lumina Neo 5G',
    price: 21999,
    description: 'Parlak ekran, uzun pil omru ve gece cekimlerinde net sonuclar veren kamera paketi sunar.',
    categoryId: 2,
    brandId: 8,
    stockCount: 21,
    imageUrl: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1200&q=80',
    summary: 'Parlak ekranli 5G telefon.',
    is_promoted: true,
  },
  {
    id: 301,
    name: 'NovaSound Max',
    price: 5499,
    description: 'Aktif gurultu engelleme ve uzun pil omru ile toplanti ve muzik kullanimina uygun kulaklik.',
    categoryId: 3,
    brandId: 1,
    stockCount: 42,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80',
    summary: 'ANC destekli kablosuz kulaklik.',
    is_promoted: true,
  },
  {
    id: 302,
    name: 'Vertex Beat Mini',
    price: 3499,
    description: 'Kompakt tasarim ve suya dayanikli yapi ile acik hava kullanimina uygun bluetooth hoparlor.',
    categoryId: 3,
    brandId: 4,
    stockCount: 47,
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80',
    summary: 'Kompakt ve guclu hoparlor.',
    is_promoted: false,
  },
  {
    id: 303,
    name: 'SkyGrid Studio Pods',
    price: 4699,
    description: 'Dusuk gecikme, cift cihaz baglantisi ve net mikrofon performansi ile gunluk kullanimda konfor saglar.',
    categoryId: 3,
    brandId: 10,
    stockCount: 53,
    imageUrl: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=1200&q=80',
    summary: 'Cift baglanti destekli kulaklik.',
    is_promoted: true,
  },
  {
    id: 401,
    name: 'Vertex Dock 8-in-1',
    price: 2299,
    description: 'USB-C, HDMI ve Ethernet gibi baglantilari tek govdede toplayan cok amacli docking istasyonu.',
    categoryId: 4,
    brandId: 4,
    stockCount: 51,
    imageUrl: 'https://images.unsplash.com/photo-1580906855284-4a0b75bb9f8a?auto=format&fit=crop&w=1200&q=80',
    summary: 'Hepsi bir arada dock cozumu.',
    is_promoted: false,
  },
  {
    id: 402,
    name: 'Arclight FastCharge 65W',
    price: 1199,
    description: 'GaN tabanli kompakt adaptor, telefon ve laptoplarda hizli sarj destegi saglar.',
    categoryId: 4,
    brandId: 3,
    stockCount: 74,
    imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=1200&q=80',
    summary: 'Kompakt hizli sarj adaptoru.',
    is_promoted: false,
  },
  {
    id: 403,
    name: 'CoreSphere Flex Stand',
    price: 899,
    description: 'Ayarlanabilir aci ve katlanabilir yapi ile tablet ve telefon kullaniminda ergonomi saglar.',
    categoryId: 4,
    brandId: 9,
    stockCount: 65,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80',
    summary: 'Katlanabilir masaustu stand.',
    is_promoted: false,
  },
  {
    id: 501,
    name: 'HelioWare Tab 11',
    price: 17499,
    description: 'Kalem destegi ve genis ekrani ile not alma, cizim ve medya tuketiminde akici deneyim sunar.',
    categoryId: 5,
    brandId: 5,
    stockCount: 23,
    imageUrl: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=1200&q=80',
    summary: 'Kalem destekli cok yonlu tablet.',
    is_promoted: true,
  },
  {
    id: 502,
    name: 'NovaSlate Plus',
    price: 20999,
    description: '120 Hz ekran ve guclu islemci ile yaratici uygulamalar icin dusuk gecikmeli kullanim sunar.',
    categoryId: 5,
    brandId: 1,
    stockCount: 17,
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=1200&q=80',
    summary: 'Yuksek tazeleme hizli tablet.',
    is_promoted: true,
  },
  {
    id: 503,
    name: 'IronPeak Pad Go',
    price: 13999,
    description: 'Hafif govde ve uzun pil omru sayesinde mobil calisma ve uzaktan egitim icin ideal bir modeldir.',
    categoryId: 5,
    brandId: 7,
    stockCount: 31,
    imageUrl: 'https://images.unsplash.com/photo-1585792180666-f7347c490ee2?auto=format&fit=crop&w=1200&q=80',
    summary: 'Tasinabilir ve uygun fiyatli tablet.',
    is_promoted: false,
  },
  {
    id: 601,
    name: 'PulseOne Strike RGB Keyboard',
    price: 2799,
    description: 'Mekanik anahtar yapisi ve ozellestirilebilir RGB profilleri ile rekabetci oyunlar icin tasarlanmistir.',
    categoryId: 6,
    brandId: 2,
    stockCount: 44,
    imageUrl: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1200&q=80',
    summary: 'Mekanik oyuncu klavyesi.',
    is_promoted: false,
  },
  {
    id: 602,
    name: 'SkyGrid Falcon Mouse',
    price: 1899,
    description: 'Yuksek DPI sensor, hafif govde ve programlanabilir tuslar ile hizli tepki verir.',
    categoryId: 6,
    brandId: 10,
    stockCount: 59,
    imageUrl: 'https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=1200&q=80',
    summary: 'Hafif ve hizli oyuncu mouse.',
    is_promoted: true,
  },
  {
    id: 603,
    name: 'QuantumEdge Aero Controller',
    price: 2399,
    description: 'Dusuk gecikmeli kablosuz baglanti ve ergonomik tutus ile konsol ve PC uyumlu gamepad deneyimi sunar.',
    categoryId: 6,
    brandId: 6,
    stockCount: 36,
    imageUrl: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=1200&q=80',
    summary: 'PC ve konsol uyumlu gamepad.',
    is_promoted: false,
  },
  {
    id: 701,
    name: 'Lumina Fit Watch 2',
    price: 6799,
    description: 'Nabiz, uyku ve egzersiz takibi yapan hafif tasarimli akilli saat modeli.',
    categoryId: 7,
    brandId: 8,
    stockCount: 33,
    imageUrl: 'https://images.unsplash.com/photo-1579586337278-3f436f25d4d4?auto=format&fit=crop&w=1200&q=80',
    summary: 'Spor odakli akilli saat.',
    is_promoted: true,
  },
  {
    id: 702,
    name: 'CoreSphere Time Pro',
    price: 8999,
    description: 'Ekran parlakligi yuksek, bildirim yonetimi guclu ve coklu spor modu sunan saat modeli.',
    categoryId: 7,
    brandId: 9,
    stockCount: 24,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80',
    summary: 'Gelisemis saglik takip ozellikleri.',
    is_promoted: false,
  },
  {
    id: 703,
    name: 'HelioWare Active S',
    price: 7499,
    description: 'Suya dayanikli govde ve haftalik pil omru ile aktif yasam tarzina uygun akilli saat.',
    categoryId: 7,
    brandId: 5,
    stockCount: 29,
    imageUrl: 'https://images.unsplash.com/photo-1511385348-a52b4a160dc2?auto=format&fit=crop&w=1200&q=80',
    summary: 'Uzun pil omurlu akilli saat.',
    is_promoted: false,
  },
  {
    id: 801,
    name: 'IronPeak Vision 27',
    price: 12499,
    description: '2K coznurluk ve 165 Hz tazeleme hizi ile hem oyun hem is kullanimina uygun monitor.',
    categoryId: 8,
    brandId: 7,
    stockCount: 19,
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80',
    summary: '2K 165 Hz oyuncu monitoru.',
    is_promoted: true,
  },
  {
    id: 802,
    name: 'SkyGrid ColorPro 32',
    price: 16999,
    description: 'Genis renk gamutu ve USB-C baglanti destegi ile icerik ureticileri icin optimize edilmistir.',
    categoryId: 8,
    brandId: 10,
    stockCount: 11,
    imageUrl: 'https://images.unsplash.com/photo-1522199755839-a2bacb67c546?auto=format&fit=crop&w=1200&q=80',
    summary: 'Renk dogru profesyonel monitor.',
    is_promoted: true,
  },
  {
    id: 803,
    name: 'NovaView Office 24',
    price: 7999,
    description: 'Dusuk mavi isik modu ve ayarlanabilir stand ile ofis kullaniminda konfor odakli ekran sunar.',
    categoryId: 8,
    brandId: 1,
    stockCount: 38,
    imageUrl: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80',
    summary: 'Ofis odakli ergonomik monitor.',
    is_promoted: false,
  },
  {
    id: 901,
    name: 'Arclight Cam 4K',
    price: 15499,
    description: 'Optik sabitleme ve 4K kayit ozelligi ile vlog ve urun cekimleri icin ideal kameradir.',
    categoryId: 9,
    brandId: 3,
    stockCount: 13,
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80',
    summary: '4K kayit yapabilen kompakt kamera.',
    is_promoted: true,
  },
  {
    id: 902,
    name: 'HelioWare Drone Mini',
    price: 22999,
    description: 'Katlanabilir govde ve otomatik takip modu ile kolay kullanim sunan baslangic seviyesi drone.',
    categoryId: 9,
    brandId: 5,
    stockCount: 8,
    imageUrl: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=1200&q=80',
    summary: 'Takip modlu kompakt drone.',
    is_promoted: false,
  },
  {
    id: 903,
    name: 'CoreSphere Action One',
    price: 11999,
    description: 'Sarsinti engelleme ve su gecirmez govde ile hareketli cekimlerde net goruntu sunar.',
    categoryId: 9,
    brandId: 9,
    stockCount: 22,
    imageUrl: 'https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?auto=format&fit=crop&w=1200&q=80',
    summary: 'Suya dayanikli aksiyon kamerasi.',
    is_promoted: false,
  },
  {
    id: 1001,
    name: 'QuantumEdge Mesh Router X',
    price: 6999,
    description: 'Cok odali evlerde stabil kapsama alani sunan mesh destekli yeni nesil router.',
    categoryId: 10,
    brandId: 6,
    stockCount: 27,
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    summary: 'Genis kapsama alanli mesh router.',
    is_promoted: true,
  },
  {
    id: 1002,
    name: 'IronPeak NAS Home 2-Bay',
    price: 13499,
    description: 'Ev ve kucuk ofis icin merkezi yedekleme ve uzaktan erisim imkani sunan NAS cihazi.',
    categoryId: 10,
    brandId: 7,
    stockCount: 16,
    imageUrl: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80',
    summary: 'Ev kullanimi icin 2 yuvali NAS.',
    is_promoted: false,
  },
  {
    id: 1003,
    name: 'SkyGrid Portable SSD 2TB',
    price: 4999,
    description: 'Yuksek okuma yazma hizi ve dayanikli govde ile buyuk dosyalari hizli tasiyabilen harici SSD.',
    categoryId: 10,
    brandId: 10,
    stockCount: 48,
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=1200&q=80',
    summary: 'Hizli ve dayanikli harici SSD.',
    is_promoted: true,
  },
];
