import type { Product } from '../types/models';

export const products: Product[] = [
  {
    id: 101,
    name: 'NovaBook Air 14',
    price: 32999,
    description:
      'NovaBook Air 14, Intel Core Ultra serisi islemci ve 16 GB RAM ile hem ofis hem de yazilim gelistirme sureclerinde hizli deneyim sunar. Mat ekran paneli uzun sureli kullanimda goz yorgunlugunu azaltir.',
    categoryId: 1,
    brandId: 1,
    stockCount: 18,
    imageUrl: 'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1200&q=80',
    summary: 'Ince tasarim, uzun pil omru ve guclu performans.',
    is_promoted: true,
  },
  {
    id: 102,
    name: 'Vertex Pro 16',
    price: 45999,
    description:
      'Vertex Pro 16, yaratici profesyoneller icin yuksek renk dogruluguna sahip 16 inç ekranla gelir. SSD depolama ve RTX destekli grafik birimi ile agir uygulamalarda akici calisir.',
    categoryId: 1,
    brandId: 4,
    stockCount: 9,
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80',
    summary: 'Yuksek performansli premium laptop.',
    is_promoted: true,
  },
  {
    id: 201,
    name: 'PulseOne X7',
    price: 24999,
    description:
      'PulseOne X7, gece cekimlerinde net sonuclar sunan 50 MP kamera sistemiyle gelir. 120 Hz ekran ve hizli sarj destegi sayesinde gun boyu yuksek performans saglar.',
    categoryId: 2,
    brandId: 2,
    stockCount: 26,
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80',
    summary: 'Kamera odakli amiral gemisi telefon.',
    is_promoted: true,
  },
  {
    id: 202,
    name: 'Arclight S10',
    price: 18999,
    description:
      'Arclight S10, dengeli fiyat-performans segmentinde 5G destegi, AMOLED ekran ve guvenli biyometrik kilit ozellikleriyle one cikar.',
    categoryId: 2,
    brandId: 3,
    stockCount: 34,
    imageUrl: 'https://images.unsplash.com/photo-1522273400909-fd1a8f77637e?auto=format&fit=crop&w=1200&q=80',
    summary: 'Gunluk kullanim icin dengeli ve hizli.',
    is_promoted: false,
  },
  {
    id: 301,
    name: 'NovaSound Max',
    price: 5499,
    description:
      'Aktif gurultu engelleme, 40 saate kadar pil omru ve dusuk gecikmeli oyun modu ile NovaSound Max kablosuz kulaklik, muzik ve toplantilar icin ideal bir secenektir.',
    categoryId: 3,
    brandId: 1,
    stockCount: 42,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80',
    summary: 'ANC destekli premium kablosuz kulaklik.',
    is_promoted: true,
  },
  {
    id: 401,
    name: 'Vertex Dock 8-in-1',
    price: 2299,
    description:
      '8 farkli baglanti noktasini tek govdede sunan Vertex Dock, USB-C, HDMI, Ethernet ve kart okuyucu destegiyle modern calisma masalarinin vazgecilmezidir.',
    categoryId: 4,
    brandId: 4,
    stockCount: 51,
    imageUrl: 'https://images.unsplash.com/photo-1580906855284-4a0b75bb9f8a?auto=format&fit=crop&w=1200&q=80',
    summary: 'Baglanti ihtiyaclari icin hepsi bir arada dock.',
    is_promoted: false,
  },
  {
    id: 103,
    name: 'NovaBook Studio 15',
    price: 39999,
    description:
      'NovaBook Studio 15, genis renk gamutuna sahip ekrani ve yuksek hizli SSD depolamasi ile tasarim ve icerik uretimi icin optimize edilmistir.',
    categoryId: 1,
    brandId: 1,
    stockCount: 12,
    imageUrl: 'https://images.unsplash.com/photo-1484788984921-03950022c9ef?auto=format&fit=crop&w=1200&q=80',
    summary: 'Yaratici is akislari icin guclu laptop.',
    is_promoted: false,
  },
  {
    id: 203,
    name: 'PulseOne Lite 5G',
    price: 15999,
    description:
      'PulseOne Lite 5G, gunluk kullanim icin optimize edilen enerji verimli islemcisi ve 2 gun dayanan pili ile fark yaratir.',
    categoryId: 2,
    brandId: 2,
    stockCount: 39,
    imageUrl: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1200&q=80',
    summary: '5G destekli fiyat performans telefonu.',
    is_promoted: false,
  },
  {
    id: 204,
    name: 'Arclight Vision Pro',
    price: 27999,
    description:
      'Arclight Vision Pro, optik sabitlemeli kamera sistemi ve yuksek parlaklik degerine sahip ekrani ile dis mekan kullaniminda ust duzey gorunurluk sunar.',
    categoryId: 2,
    brandId: 3,
    stockCount: 15,
    imageUrl: 'https://images.unsplash.com/photo-1512499617640-c2f999018b72?auto=format&fit=crop&w=1200&q=80',
    summary: 'Parlak ekranli ust segment telefon.',
    is_promoted: true,
  },
  {
    id: 302,
    name: 'Vertex Beat Mini',
    price: 3499,
    description:
      'Kompakt tasarimi ve IPX5 suya dayaniklilik ozelligi ile Vertex Beat Mini, hareketli yasam tarzina uygun bir bluetooth hoparlordur.',
    categoryId: 3,
    brandId: 4,
    stockCount: 47,
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80',
    summary: 'Kompakt ve guclu ses veren hoparlor.',
    is_promoted: false,
  },
  {
    id: 303,
    name: 'PulseOne AirBuds Pro',
    price: 4299,
    description:
      'Hibrit aktif gurultu engelleme ve cift cihaz baglantisiyla PulseOne AirBuds Pro, gunluk kullanimda konfor ve net ses sunar.',
    categoryId: 3,
    brandId: 2,
    stockCount: 58,
    imageUrl: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=1200&q=80',
    summary: 'Cift baglanti destekli kablosuz kulaklik.',
    is_promoted: true,
  },
  {
    id: 402,
    name: 'Arclight FastCharge 65W',
    price: 1199,
    description:
      'GaN teknolojisi sayesinde daha kucuk boyutta yuksek verim sunan Arclight 65W adaptoru, laptop ve telefonlarda hizli sarji destekler.',
    categoryId: 4,
    brandId: 3,
    stockCount: 74,
    imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=1200&q=80',
    summary: 'Kompakt govdede yuksek guclu sarj adaptoru.',
    is_promoted: false,
  },
];

